"""initial

Revision ID: 957314f565d4
Revises: 
Create Date: 2026-01-27 23:10:24.958225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '957314f565d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('substation', sa.String(length=200), nullable=False),
    sa.Column('component_type', sa.Enum('transformer', 'line', 'switch', name='component_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_component_type'), 'components', ['component_type'], unique=False)
    op.create_index(op.f('ix_components_name'), 'components', ['name'], unique=False)
    op.create_index(op.f('ix_components_substation'), 'components', ['substation'], unique=False)
    op.create_index('ix_components_type_substation', 'components', ['component_type', 'substation'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='report_status'), nullable=False),
    sa.Column('from_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('job_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('components_by_type_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transformer_capacity_by_voltage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('line_length_by_voltage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('daily_measurement_averages_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('manager', 'user', name='user_role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('voltage_kv', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('measurement_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_component_id'), 'measurements', ['component_id'], unique=False)
    op.create_index('ix_measurements_component_type_time', 'measurements', ['component_id', 'measurement_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_measurements_measurement_type'), 'measurements', ['measurement_type'], unique=False)
    op.create_index(op.f('ix_measurements_timestamp'), 'measurements', ['timestamp'], unique=False)
    op.create_table('switches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='switch_status'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transformers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capacity_mva', sa.Float(), nullable=False),
    sa.Column('voltage_kv', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transformers')
    op.drop_table('switches')
    op.drop_index(op.f('ix_measurements_timestamp'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_measurement_type'), table_name='measurements')
    op.drop_index('ix_measurements_component_type_time', table_name='measurements')
    op.drop_index(op.f('ix_measurements_component_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('lines')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_components_type_substation', table_name='components')
    op.drop_index(op.f('ix_components_substation'), table_name='components')
    op.drop_index(op.f('ix_components_name'), table_name='components')
    op.drop_index(op.f('ix_components_component_type'), table_name='components')
    op.drop_table('components')
    # ### end Alembic commands ###
